version: '3.8'

networks:
  internal: null
  proxy:
    attachable: true
    name: proxy


services:
  frontend:
    container_name: webkinz-frontend-prod
    image: docker-nextjs-dev
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.webkinz.rule: Host(`webkinz.awot.dev`)
      traefik.http.routers.webkinz.entrypoints: websecure
      traefik.http.routers.webkinz.tls: true
      com.centurylinklabs.watchtower.enable: false
    networks:
      - internal
      - proxy

  backend:
    container_name: webkinz-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /usr/src/app/node_modules
      - ./backend/app:/usr/src/app
    ports:
      - 5000:5000
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.webkinz-api.rule: Host(`webkinz-api.awot.dev`)
      traefik.http.routers.webkinz-api.entrypoints: websecure
      traefik.http.routers.webkinz-api.tls: true
      traefik.http.services.webkinz-api.loadbalancer.server.port: 5000
      com.centurylinklabs.watchtower.enable: false
    networks:
      - internal
      - proxy

