version: '3.8'

networks:
  internal: null
  proxy:
    attachable: true
    name: proxy

services:
  frontend:
    container_name: webkinz-frontend-prod
    image: docker-nextjs-dev
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.webkinz.rule: Host(`webkinz.awot.dev`)
      traefik.http.routers.webkinz.entrypoints: websecure
      traefik.http.routers.webkinz.tls: true
      com.centurylinklabs.watchtower.enable: false
    networks:
      - internal
      - proxy