version: '3.8'

services:
  frontend:
    container_name: frontend
    image: docker-nextjs-dev
    build: ./frontend
    volumes:
      - ./frontend/app/api:/app/api
      - ./frontend/app/components:/app/components
      - ./frontend/app/pages:/app/pages
      - ./frontend/app/public:/app/public
      - ./frontend/app/styles:/app/styles
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend: null
