version: '3.8'

services:
  frontend:
    container_name: webkinz-frontend-prod
    image: docker-nextjs-dev
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - frontend

  backend:
    container_name: webkinz-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /usr/src/app/node_modules
      - ./backend/app:/usr/src/app
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - frontend

  # db:
  #   container_name: postgres
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-pern_db}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
  #     PGDATA: /var/lib/postgresql/data
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data
  #     - ./postgres/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - db
  #   restart: unless-stopped

  # db_manager:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   volumes:
  #     - ./postgres/pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - db
  #   restart: unless-stopped

networks:
  frontend: null
  # db:
  #   driver: bridge
