name: first-github-action
on: [push]
jobs:
  write-to-console:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
         echo 'Hello world!'
         ls
      - run: echo "test"