name: first-github-action
on: [push]
jobs:
  write-to-console:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Git
        run: |
          git pull origin master
      - name: Backend
        run: |
         cd backend
         ls
      - name: Frontend
        run: |
         cd frontend
         ls
         