name: first-github-action
on: [push]
jobs:
  deploy-on-server:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Git
        run: |
          git pull origin master
      - name: Backend
        run: |
         cd backend/app
         ls
      - name: Frontend
        run: |
         cd frontend
         ls
      - name: Build docker compose
        run: docker compose -f docker-compose-prod.yml up -d --build --wait
      - name: Check running containers
        run: docker ps -a
      - name: Docker compose Down
        run: docker compose -f docker-compose-prod.yml down