name: first-github-action
on: [push]
jobs:
  deploy-on-server:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Git
        run: |
          git pull origin master
      - name: Backend
        run: |
         cd backend/app
         ls
      - name: Frontend
        run: |
         cd frontend
         ls
      - name: Build & start containers
        run: docker compose -f docker-compose-prod.yml up -d --build --wait
      - name: Check running containers
        run: docker ps --format "{{.Names}} \t{{.ID}} \t{{.Status}}"
        
      - name: Stop containers
        run: docker compose -f docker-compose-prod.yml down